# Generated by Django 3.2.6 on 2021-11-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blog',
            name='topic',
            field=models.ManyToManyField(to='blog.Topic'),
        ),
    ]
