# Generated by Django 3.2.6 on 2021-11-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211126_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='topic',
            new_name='topics',
        ),
    ]
