# Generated by Django 3.2.6 on 2021-11-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_topic_blog_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='topics',
        ),
        migrations.AddField(
            model_name='topic',
            name='blogs',
            field=models.ManyToManyField(to='blog.Blog'),
        ),
    ]
