# Generated by Django 3.2.6 on 2021-12-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blog',
            name='topics',
            field=models.ManyToManyField(to='blog.Topic'),
        ),
    ]
